[package]
name = "mirar"
version = "0.1.0"
authors = [" <>"]

[dependencies]
iron = "*"
router = "*"
hyper = "*"
urlencoded = "*"
reqwest = "*"
serde_json = "*"
serde_urlencoded = "*"
serde_derive = "*"
serde = "*"